### PR TITLE
fix batchmatmul params for bladnn::gemm()

### PR DESCRIPTION
**Pull request by minminsun**

### CODE REVIEW

**Review by fortianyou — COMMENTED** [review]
Nit: How about add a UT to check it?

**Comment by qiuxiafei** [comment]
> Nit: How about add a UT to check it?

These lines are built under `PLATFORM_ALIBABA` macro, maybe the tests could only be added to internal repositoryl, i think ...

**Comment by minminsun** [comment]
I think it's OK to add in this repo some MatMul and Batchmatmul tests, which will run in both external ci (without bladnn) and internal ci(with bladnn). Thanks @fortianyou @qiuxiafei

**Review by qiuxiafei — APPROVED** [review]
LGTM~

**Pull request merged**
