### PR TITLE
only deploy docker on schedule

### PR DESCRIPTION
**Pull request by Yancey1989**

### CODE REVIEW

**Comment by qiuxiafei** [comment]
Is it needed for tf?

**Comment by Yancey1989** [comment]
> Is it needed for tf?

just to keep all runtime Docker comes from the same codebase.

**Comment by Yancey1989** [comment]
> Is it needed for tf?

@qiuxiafei  Sure, I updated this PR, thanks.

**Review by qiuxiafei — APPROVED** [review]
LGTM~

**Pull request merged**
