### PR TITLE
fix merge conflict

### PR DESCRIPTION
**Pull request by wyzero**

### CODE REVIEW

**Review by Yancey1989 — APPROVED** [review]
LGTM!

**Comment by Orion34-lanbo** [comment]
This is because is `disc-dynamic-slice-converter` pass's ci run last Friday，however it is merged this morning... My bad....

**Comment by Yancey1989** [comment]
> This is because is disc-dynamic-slice-converter pass's ci run last Friday，however it is merged this morning... My bad....

It's okay, a better way to guarantee the codebase is correct is to force enable **REBASE** before merging on Github website, but it's hurt the merging and developing efficiency, maybe we can have a discussion about whether to enable it or not.

**Comment by qiuxiafei** [comment]
@Yancey1989 Once we tried `fast-forward-only` merge in internal repo, it did hurt...😂

**Pull request merged**
